server:
  port: 8082
  servlet:
    context-path: /producer2
    application-display-name: producer2

spring:
  application:
    name: dubboProducer2

#dubbo相關屬性
dubbo:
  application:
    name: provider-server
  registry: #註冊中心地址
    address: zookeeper://127.0.0.1:2181 #, multicast://127.0.0.1:88888
  scan:
    base-packages: com.dubbo.producer.service
  protocol:
    port: 20882 #透過dubbo開放服務供給對外開放的port
  metadata-report: #要在dubbo-admin 服務信息及原數據能夠看到服務提供者開放的服務方法
    address: zookeeper://127.0.0.1:2181
  provider:
    loadbalance: leastactive
admin: #要在dubbo-admin 服務信息及原數據能夠看到服務提供者開放的服務方法
  config-center: zookeeper://127.0.0.1:2181



