server:
  port: 8081
  servlet:
    context-path: /producer
    application-display-name: producer

spring:
  application:
    name: dubboProducer

#dubbo相關屬性
dubbo:
  application:
    name: provider-server
  registry: #註冊中心地址
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.dubbo.producer.service




